[tox]
envlist = py{310,311,312}-django{42,52}
    py{312,313}-django{52,60}

[testenv]
commands = coverage run --parallel -m pytest {posargs}
deps =
    -r{toxinidir}/requirements.txt
    django42: django>=4.2,<4.3
    django52: django>=5.2,<5.3
    django60: django>=6.0,<6.1

[testenv:lint]
basepython = python3.11
deps =
    flake8
    isort
commands =
    make lint

[testenv:coverage-report]
basepython = python3.11
deps = coverage
skip_install = true
commands =
    coverage combine
    coverage report
